name: Lint

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          architecture: 'x64'

      - name: Setup Node.js 13.12.0
        uses: actions/setup-node@v1
        with:
          node-version: 13.12.0

      - name: Setup Danger
        run: |
          gem install bundler
          bundle install

      - name: Fetch cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-${{ github.ref }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.ref }}
            ${{ runner.os }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linter
        run: yarn lint

      - name: Run Danger
        run: bundle exec danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

